controller_list:
  - name: fake_sia5_controller
    joints:
      - leftjoint_s
      - leftjoint_l
      - leftjoint_e
      - leftjoint_u
      - leftjoint_r
      - leftjoint_b
      - leftjoint_t
  - name: fake_ur5_controller
    joints:
      - rightshoulder_pan_joint
      - rightshoulder_lift_joint
      - rightelbow_joint
      - rightwrist_1_joint
      - rightwrist_2_joint
      - rightwrist_3_joint
  - name: fake_dual_manipulator_controller
    joints:
      - leftjoint_s
      - leftjoint_l
      - leftjoint_e
      - leftjoint_u
      - leftjoint_r
      - leftjoint_b
      - leftjoint_t
      - rightshoulder_pan_joint
      - rightshoulder_lift_joint
      - rightelbow_joint
      - rightwrist_1_joint
      - rightwrist_2_joint
      - rightwrist_3_joint